# Generated by Django 4.2.16 on 2024-11-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
