# Generated by Django 4.2.16 on 2024-11-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
